### ISSUE TITLE
TST: pytest on databroker can't be run on MacOS

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAn#15]
mostly because ``mongo`` backed ``db`` can't be created.

Still digging into this issue

**Comment by CJ-Wright** [comment]
Does mongo/pymongo work on mac? If not we can use the protable mds/fs which are sqlite based

**Comment by chiahaoliu** [comment]
yes, I would tend to do that. also I found a useful resource here:

https://github.com/NSLS-II/broker-tutorial/blob/master/generate_data.py
credit:  @danielballan

it creates ``db`` and feed data with real ``RE``

Should I do a PR?

**Comment by CJ-Wright** [comment]
That sounds great, although I would just be wary of what `det` hands back. Is it a 2D detector? We can then integrate it into the `conftest.py`

**Comment by chiahaoliu** [comment]
``det`` can take a function to create designed output, I can deal with that part

question pop out during the refactoring. does ``finalizaer`` always needed for test?

**Comment by danielballan** [comment]
Finalizer is optional but should be used if you create anything (in my
case, a test database) that should be cleaned up.

**Comment by CJ-Wright** [comment]
Reading through the example again, we might try to test against both the portable and mongo based dbs. That way we support both systems, just in case there is any difference. We can put in a conditional known fail if mongo doesn't exist.

**Comment by danielballan** [comment]
Regarding the title of this issue, I run the databroker (and metadatastore and portable-mds) tests on OSX, no problem. Mongo works and is installable easily using homebrew. You do need to have a mongo daemon running when you run the tests.

**Comment by chiahaoliu** [comment]
Here is my error msg:

````
self = <metadatastore.mds.MDS object at 0x113f44d68>

    @property
    def _connection(self):
        if self.__conn is None:
            if self.auth:
>               uri = 'mongodb://{0}:{1}@{2}:{3}/'.format(self.config['mongo_user'],
                                                          self.config['mongo_pwd'],
                                                          self.config['host'],
                                                          self.config['port'])
E               KeyError: 'mongo_user'

../metadatastore/metadatastore/mds.py:91: KeyError
````

maybe I didn't configure my mongo correctly ?

**Comment by CJ-Wright** [comment]
Did you install from source or conda?

**Comment by chiahaoliu** [comment]
source, no conda package for OSX

**Comment by danielballan** [comment]
Wherever the MDS object is instantiated, pass the keyword arg `auth=False`, and things will work as before. The latest release of MDS includes optional authentication (on by default) which expects additional configuration. There is no reason to use this in testing, though.

**Comment by chiahaoliu** [comment]
``auth=False`` does do the trick

**Comment by sbillinge** [comment]
please put a message when you close the issue.  Was it resolved?  If so, link to the commit or PR is good.
