### ISSUE TITLE
Python 2.7 compatibility?

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAn#16]
Do we want to make xpdAn python 2.7 compatible?
Some of our analysis stack might be only 2.7 safe (looking at you srFit).
What do you think @sbillinge?
(Props to Soham for bringing this up @sbanerjee23)

**Comment by sbillinge** [comment]
I would rather work to make SrFit py3.  But would there be much involved to make An 2.7 compatible?

**Comment by CJ-Wright** [comment]
Actually, I am starting to think we should just bring SrFit into py3 rather than support legacy python. They syntax that py3k allows is much cleaner.
