### ISSUE TITLE
ENH: use advanced templating to customize folder_tag_list

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAn#173]
We need to use some advanced templating to take advantage of `folder_tag_list`
Something along the lines of this somewhere in `render_and_clean`
```python
from xpdan.formatters import render_and_clean, pfmt
md = {'bla': 1, 'foo': 2, 'spam': {'eggs': {'parrot': 'hi'}, 'bacon': 2},
      'folder_tag_list': ['bla', 'foo', ('spam', 'eggs', 'parrot')]}

base_template = (''
                 '{folder_tag_stuff}/'
                 '{analyzed_start[analysis_stage]}/'
                 '{raw_start[sample_name]}_'
                 '{human_timestamp}_'
                 '[temp={raw_event[data][temperature]:1.2f}'
                 '{raw_descriptor[data_keys][temperature][units]}]_'
                 '[dx={raw_event[data][diff_x]:1.3f}'
                 '{raw_descriptor[data_keys][diff_x][units]}]_'
                 '[dy={raw_event[data][diff_y]:1.3f}'
                 '{raw_descriptor[data_keys][diff_y][units]}]_'
                 '{raw_start[uid]:.6}_'
                 '{raw_event[seq_num]:03d}{ext}')


a = ''
for k in md['folder_tag_list']:
    if isinstance(k, str):
        z = str(md[k])
    else:
        sub_md = md.copy()
        for kk in k:
            sub_md = sub_md[kk]
        z = str(sub_md)
    a += z +'/'
print(a)

formatted_base_template = pfmt.format(base_template, folder_tag_stuff=a)
# base_template.format(folder_tag_stuff=a)
print(formatted_base_template)

# b = render_and_clean(a, raw_start=md)
# print(b)
print(md)
```

**Comment by eaculb** [comment]
Hi Chris,
I've been working on this a bunch today but have a question before submitting my next PR. I have a sample yaml file I've been using as metadata when writing tests (currently saved in the tests folder) but I'm not sure where in the overarching test suite we're providing that kind of external data (e.g. how the database being searched properly gets passed into your fuzzybroker tests).

Of course I can go ahead and put in a PR for everything I currently have if that's what you want to do, regardless of the fact that the example metadata almost certainly isn't being dealt with properly. Maybe we can chat tomorrow in general about how to run tests myself before submitting a PR. The architecture of the test suite is still a little fuzzy to me.

**Comment by CJ-Wright** [comment]
Sure, we can talk about the database test fixtures tomorrow.

**Comment by CJ-Wright** [comment]
I think this is done now!
