### ISSUE TITLE
ANN: bluesky-0mq-proxy is now running as a service

### ISSUE THREAD

**Issue by danielballan** [xpdAcq/xpdAn#206]
I think this is the relevant repo to announce this in. DAMA now takes responsibility for deploying `bluesky-0mq-proxy` as a long-running, monitored service at XPD and PDF. See confirmation on `xf28id-ca1` and `xf28id1-ca1`:

```
dallan@xf28id-ca1:~$ sudo supervisorctl status
bluesky-zmq                      RUNNING    pid 7054, uptime 0:01:33
dallan@xf28id-ca1:~$ tail /var/log/bluesky-zmq.out.log
Loading...
Connecting...
Receiving on port 5577; publishing to port 5578.
```

```
dallan@xf28id1-ca1$ sudo supervisorctl status
bluesky-zmq                      RUNNING    pid 51348, uptime 0:01:01
dallan@xf28id1-ca1$ tail /var/log/bluesky-zmq.out.log
Loading...
Connecting...
Receiving on port 5577; publishing to port 5578.
```

Error logs are located at `/var/log/bluesky-zmq.err.log`.

attn @CJ-Wright

**Comment by CJ-Wright** [comment]
Is there an IP address I should be using in the dispatcher, or can I just do `xf29id-ca1: 5578`?

**Comment by CJ-Wright** [comment]
Also will it be possible to do this on the XPD beamline (xf28id2)?

**Comment by danielballan** [comment]
> Is there an IP address I should be using in the dispatcher, or can I just do xf28id-ca1: 5578?

The hostname is a more stable identifier than the IP address. Yes, you should use that.

> Also will it be possible to do this on the XPD beamline (xf28id2)?

I believe the `xf28id` (with no trailing number) is on the XPD subnet and should be accessible there.

**Comment by CJ-Wright** [comment]
I'm closing this issue as we are using this at XPD and PDF to great success!
