### ISSUE TITLE
automask workflow described in documentation

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAn#22]
<a href="https://github.com/sbillinge"><img src="https://avatars.githubusercontent.com/u/4254545?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sbillinge](https://github.com/sbillinge)**
_Wednesday Sep 28, 2016 at 15:33 GMT_
_Originally opened as https://github.com/xpdAcq/xpdAcq/issues/223_

----

on cheatsheet, and in quickstart and main part of documentation

**Comment by CJ-Wright** [comment]
<a href="https://github.com/CJ-Wright"><img src="https://avatars.githubusercontent.com/u/6740689?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CJ-Wright](https://github.com/CJ-Wright)**
_Wednesday Sep 28, 2016 at 15:41 GMT_

----

Is there one documentation going out for the combined Acq and An repos?

**Comment by CJ-Wright** [comment]
<a href="https://github.com/sbillinge"><img src="https://avatars.githubusercontent.com/u/4254545?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sbillinge](https://github.com/sbillinge)**
_Wednesday Sep 28, 2016 at 16:23 GMT_

----

one user documentation.  

Developer docs are all in the codes and so are somewhat separated.

**Comment by CJ-Wright** [comment]
see xpdAcq/xpdAcq/#227

**Comment by sbillinge** [comment]
whoops, mistakenly put this on the PR and not here....but that is fixed now!

might want to reopen this issue, or a new one...I don't think there is user documentation for the auto-mask capability, though its use is there in the workflow.

This should definitely be in the An side of things though, so if we create a separate xpdAn user-doc (which I think we need) it should go in there, and attached to v0.6 release.

**Comment by CJ-Wright** [comment]
I wrote some automasking docs which went into the doc pr. I agree that we should have two sets of user docs
