### ISSUE TITLE
MTN: Glbl to Dict

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAn#30]
We may be able to perform all the functionality of the `Glbl` object with a dict. The object has no methods or other OO features so this should be mostly painless. The added benefit of dict is that we can have different globals overlap safely (eg xpdAn and xpdAcq).

**Comment by sbillinge** [comment]
yes, I dislike the `glbl`.  That was something that we struggled with a lot and got working, so we should go away from it cautiously, but it has the odour of inelegance about it.

Perhaps we can start a branch that just explores this issue and decide if it should be refactored for the next release or not.  We should also not move away from the `glbl` solution until we are sure that we are getting something better.

**Comment by CJ-Wright** [comment]
In discussion with @chiahaoliu, we might go with a subclass of YAML dict which will allow the global to be dynamically saved and reloaded as needed.

**Comment by CJ-Wright** [comment]
see #87

**Comment by CJ-Wright** [comment]
Closed by #87
