### ISSUE TITLE
need a function to start analysis

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAn#33]
as we have ``_start_beamtime`` in collection side, we want to have a similar function like ``start_analysis`` which inherits information from ``bt`` at collection side.

During beamtime, we still want images and analysis results be saved inside``xpdUser`` at workstation2, so that our ``end_beamtime`` function is still reusable.

**Comment by CJ-Wright** [comment]
Is this for this release or future releases?

**Comment by chiahaoliu** [comment]
for this release we would have a temperate solution that reads in ``bt_bt.yml`` but we could potentially have a better solution.
