### ISSUE TITLE
[request] Reduced data in tiff_base 

### ISSUE THREAD

**Issue by sbanerjee23** [xpdAcq/xpdAn#34]
While we are file based, and dependent on tiff_base for analysis at the beam line could we:
- Remove the "Ni_calibrant" sample from the template import table.  This becomes ambiguous with the "Ni" dir that stores Ni files from run_calibration. Ni is not a "sample", it is always a calibrant. The idea to preload bt list with a "test" sample object is better. 
- If it is necessary to store integrated data on both a q(nm^-1) and q(2-theta) grid in the same tiff_base dirs as the images, could we make separate subdirs for them please? Better idea might be to start storing all reduced data outside of tiff_base (pe2). @CJ-Wright

**Comment by sbillinge** [comment]
why?

**Comment by CJ-Wright** [comment]
I'm not certain about the "Ni_calibrant" but I'm now working on writing reduced data directly from the analysis pipeline.

**Comment by CJ-Wright** [comment]
Proposed new dir structure for general data:
`.../tiff_base/sample_name/folder_tag/analysis_stage/human_timestamp_auxiliary.ext`
- folder_tag is user defined in the metadata (after_dinner, SAXS, happy_data) whatever the user would like. This kills many birds with one stone: a) it encourages users to write rich metadata, b) it takes the place of making wonky sample names to accurately capture data, c) users can put like data together for ease of processing
- analysis_stage is from the pipeline and tells us what kind of data is being written (raw, dark_sub, chi, pdf, etc.)
- human_timestamp is a human readable timestamp (as we have it now)
- auxiliary is where any additional data goes (motor position, temperature, etc.)

Darks will also be saved in a dark folder for the entire beamtime:
`.../tiff_base/dark/human_timestamp.ext`

This is provided as a just-in-case. The users can back calculate which dark they want to use (or play even more advanced games with interpolation, smoothing, etc.) by comparing timestamps on their light data and their dark data.

**Comment by CJ-Wright** [comment]
Note that is the tag is not specified then we will go from sample to analysis stage

**Comment by CJ-Wright** [comment]
Closed by #107
