### ISSUE TITLE
Masking convention

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAn#36]
Since it has been a bit of a hot topic, I thought I would open an issue here so we can discuss potential masking conventions.
My understanding is that there are two conventions:
- `0/False` is a good pixel (shared by [pyFAI](https://github.com/silx-kit/pyFAI/blob/561f0b8f46579708d16009f069305cd76b062509/pyFAI/azimuthalIntegrator.py#L226), and [SrX](https://github.com/diffpy/diffpy.srxplanar/blob/4b2a146b9a4756b36a0a3e157df49c39740b807a/diffpy/srxplanar/mask.py))
- `1/True` is a good pixel (shared by [skbeam](https://scikit-beam.github.io/scikit-beam/resource/api/core/mask.html), [skimage](http://scikit-image.org/docs/dev/user_guide/numpy_images.html#numpy-indexing) and xpdAn (currently)

Thoughts @sbillinge @chiahaoliu @tacaswell @danielballan

**Comment by danielballan** [comment]
Ref. on scikit-image convention: http://scikit-image.org/docs/dev/user_guide/numpy_images.html#numpy-indexing

**Comment by tacaswell** [comment]
non-zero as good also fits in very well with the label-based ROI code (0 is background, positive integers are labeled ROIs). 

What is the advantage of 0 -> good mapping?

**Comment by sbillinge** [comment]
none, except consistency with industry-standard codes that picked the wrong
convention and then institutionalized it. Like ending up with the charge on
the electron being negative still 200 years later, this shouldn't be
underestimated.  We don't need to change any code internally, but we need a
way to feed out masks to pyFai, SrX and fit2D that they like.

**Comment by CJ-Wright** [comment]
I asked pyFAI about their convention, here was their reply: silx-kit/pyFAI#443

**Comment by chiahaoliu** [comment]
If I understand correctly, it seems pyFAI is heading to the direction of 1 being masked pixel, though it might not be complete yet according to kiv's comment. 

This convention will meet Chris' convention. However, we still need to invert it before feeding it into integration engine for correct result at this stage.

Does it has to do with numpy related algo as kiv pointed out, or other reason?

**Comment by CJ-Wright** [comment]
Closing, we are going with the NSLS-II standard
