### ISSUE TITLE
Make sure the Columbia/Billinge-group copyright statement appears in all the An files

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAn#56]
please see issue #316 in Acq for details of scope, but basically code files but not documentation files.

**Comment by CJ-Wright** [comment]
For some reason the reference didn't work see xpdAcq/xpdAcq#316

**Comment by CJ-Wright** [comment]
We should write a script which checks if all python files have the desired copyright, this way travis can fail if we are missing the copyright text.

This package might also be helpful.
https://github.com/rsmz/copyright

**Comment by CJ-Wright** [comment]
Would it be possible to have the copyright loaded as a string into `__copyright__`?
This would a) make it easier to test if the copyright exists and is correct and b) accessible at runtime upon import.

**Comment by sbillinge** [comment]
Not sure, I would have to look at that. Let's discuss briefly on Monday?

**Comment by CJ-Wright** [comment]
Of course!
