### ISSUE TITLE
MTN: need way to capture pipelines in a way such that they are modular

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAn#83]
Currently the only ways to extend a pipeline are to a) take the output stream from the pipeline and use it or b) copy the pipeline and insert the new code into it somewhere.

While a) is fine b) is not as it results in a large amount of code rewrite for the addition of potentially one line of code.

Personally I like Dask's approach of using a dictionary with `{'new_data_name': (function, inputs)}'. This allows new nodes to be added to the task graph in a pythonic way, just update the dictionary. Dask seems to be able to handle this in its threading scheduler, though not it its multiprocessing or distributed scheduler due to non-pickelable generator issues.

Thoughts @danielballan @tacaswell?

Update: it seems that dask threading does not do the needed tee'ing for the generators to be preserved.

**Comment by mrocklin** [comment]
I apologize for injecting myself into this conversation.  I decided to do a github search on Dask (it's fun seeing what pops up).

If the elements of your iterators are sizable then you may benefit from dask's handling of queues or channels.

- http://distributed.readthedocs.io/en/latest/channels.html
- http://distributed.readthedocs.io/en/latest/queues.html

I've been looking for an open source user of channels for a while.  It would be nice to have more publicly accessible examples of their use.

**Comment by CJ-Wright** [comment]
No need to apologize, we're very happy to have your input.

Channels seems like it might help us quite a bit. Currently we are in the position of having a [task graph](https://github.com/CJ-Wright/xpdAn/blob/5ef9c38440b4a77ed928721e33c98bed40bff122/examples/xpd_pipeline.pdf) and a bunch of data which is in a queue/generator. 

Each of the nodes in the task graph is currently formulated as a generator so that it can expand and contract the number of outputs as needed (a filter node just doesn't yield the data if it doesn't meet the criteria) and store a small amount of state. 

Would it be possible to give an example of how channels could be used with an existing task graph and/or with generators?

(I'm more than happy to talk about this in more depth off-line if you want, my email is cjwright4242@gmail.com)

**Comment by CJ-Wright** [comment]
Closing since streams exists now
